site_name: UMTRI CARLA GUI BACKEND GUIDE
docs_dir: Docs
theme: readthedocs


nav:
    - Home: index.md
    - Installation Guide: installation_guide.md
    - Urban Backend Introduction: urban_backend_introduction.md
    - Urban Backend API: urban_backend_api.md
    - Freeway Backend Introduction: freeway_backend_introduction.md
    - Freeway Backend API: freeway_backend_api.md
